# Generated by Django 4.0 on 2022-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_moderator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='unit',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
