# Generated by Django 4.0 on 2022-04-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_needed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='facility',
            field=models.CharField(choices=[('MPH', 'MPH'), ('Auditorium', 'Auditorium'), ('Parade Square', 'Parade Square')], max_length=100, null=True),
        ),
    ]
