# Generated by Django 4.0 on 2022-04-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bookingrequest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='event_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
