# Generated by Django 4.0 on 2022-04-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='updated_by_admin',
        ),
    ]
