# Generated by Django 4.0 on 2022-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_bookingrequest_updated_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='date_needed',
            new_name='date',
        ),
    ]
