# Generated by Django 4.0 on 2022-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_date_needed_bookingrequest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='description',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='date_needed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='time_needed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
