# Generated by Django 4.0 on 2022-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_description_bookingrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_needed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='time_needed',
            field=models.TimeField(null=True),
        ),
    ]
