# Generated by Django 4.0 on 2022-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_bookingrequest_date_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='time_needed',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
