# Generated by Django 4.0 on 2022-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_time_needed_bookingrequest_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='reason',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='updated_by_admin',
            field=models.DateTimeField(null=True),
        ),
    ]
