# Generated by Django 4.0 on 2022-04-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_reason_bookingrequest_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='customer',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='updated_by_admin',
        ),
    ]
