# Generated by Django 4.0 on 2022-04-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_bookingrequest_priority_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='date_needed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='event_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='facility',
            field=models.CharField(choices=[('Conference Room', 'Conference Room'), ('Futsal Court 1', 'Futsal Court 1'), ('Futsal Court 2', 'Futsal Court 2'), ('Gym', 'Gym'), ('IPPT Running Route', 'IPPT Running Route'), ('Lecture Theatre', 'Lecture Theatre'), ('Mess', 'Mess'), ('Multi Purpose Hall', 'Multi Purpose Hall'), ('Parade Square (2SIR) Left', 'Parade Square (2SIR) Left'), ('Parade Square (5SIR) Right', 'Parade Square (5SIR) Right'), ('Planning Room (505)', 'Planning Room (505)'), ('Training Shed 603A', 'Training Shed 603A'), ('Training Shed 603B', 'Training Shed 603B'), ('VIP Lounge', 'VIP Lounge'), ('Ballinger Running Route', 'Ballinger Running Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='priority_lvl',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
