# Generated by Django 4.0 on 2022-04-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_bookingrequest_priority_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='ending_time',
            field=models.IntegerField(choices=[(820, '08:20'), (920, '09:20'), (1020, '10:20'), (1110, '11:10'), (1220, '12:20'), (1420, '14:20'), (1520, '15:20'), (1610, '16:10'), (1720, '17:20'), (1810, '18:10'), (2100, '21:00')], default=720),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='starting_time',
            field=models.IntegerField(choices=[(730, '07:30'), (820, '08:20'), (930, '09:30'), (1020, '10:20'), (1130, '11:30'), (1330, '13:30'), (1430, '14:30'), (1520, '15:20'), (1630, '16:30'), (1720, '17:20'), (1930, '19:30')], default=730),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
