# Generated by Django 4.0 on 2022-04-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_bookingrequest_ending_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='start_time',
        ),
    ]
