# Generated by Django 4.0 on 2022-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_bookingrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='POC',
            field=models.CharField(default='nil', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='num_pax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
