# Generated by Django 4.0 on 2022-04-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_bookingrequest_poc_bookingrequest_num_pax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='num_pax',
            new_name='number_of_pax',
        ),
    ]
