# Generated by Django 4.0 on 2022-04-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_event_title_bookingrequest_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='description',
            new_name='remarks',
        ),
    ]
