# Generated by Django 4.0 on 2022-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_description_bookingrequest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='facility',
            field=models.CharField(choices=[('Conference Room', 'Conference Room'), ('Futsal Court 1', 'Futsal Court 1 (closer to BDE)'), ('Futsal Court 2', 'Futsal Court 2 (closer to 2SIR)'), ('Gym', 'Gym'), ('IPPT Running Route', 'IPPT Running Route'), ('Lecture Theatre', 'Lecture Theatre/Auditorium'), ('Mess', 'Mess'), ('Multi Purpose Hall', 'Multi Purpose Hall'), ('Parade Square (2SIR) Left', 'Parade Square (2SIR) Left'), ('Parade Square (5SIR) Right', 'Parade Square (5SIR) Right'), ('Planning Room (505)', 'Planning Room (505)'), ('Training Shed 603A', 'Training Shed 603A'), ('Training Shed 603B', 'Training Shed 603B'), ('VIP Lounge', 'VIP Lounge'), ('Ballinger Running Route', 'Ballinger Running Route')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='priority_level',
            field=models.IntegerField(choices=[(1, '1 (Bilat/ROT/Test)'), (2, '2 (UTS Training Activities)'), (3, '3 (Admin/Cohesion Activities')]),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='starting_time',
            field=models.IntegerField(choices=[(730, '07:30 (Period 1)'), (820, '08:20 (Period 2)'), (930, '09:30 (Period 3)'), (1020, '10:20 (Period 4)'), (1130, '11:30 (Period 5)'), (1330, '13:30 (Period 6)'), (1430, '14:30 (Period 7)'), (1520, '15:20 (Period 8)'), (1630, '16:30 (Period 9)'), (1720, '17:20 (Period 10)'), (1930, '19:30 (Night)')]),
        ),
    ]
